export let whiteArrow = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/leftarrowfinal.png";
export let greenHash  = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/hash.png";
export let blackCard  = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/blackvisa.png";
export let greenArrow = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/smallarrow.png";
export let personHead = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/head.png";
export let googlePay  = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/gpay.png";
export let plusIcon   = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/plusicon.png";
export let masterCard = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/mastercard.png";
export let visaCard   = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/visa.png";
export let mnpPayment = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/mnp.png";
export let blackCross = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/blackcross.png";
export let blueArrow  = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/bluearrow.png";
export let successGif = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/successgif.gif";
export let fbLogo     = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/fb.png";
export let googleLogo = "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/google.png";
export let failureIcon= "https://imagesdataporter.s3.ap-south-1.amazonaws.com/Eco-Resource/failureicon.png"